

/**
 * Maps language names to their most representative country flag emoji.
 * Extend this as needed for new languages.
 */
export function languageToFlag(language: string): string {
  console.log("🏳️ languageToFlag called with:", language);
  
  const mapping: Record<string, string> = {
    English: "🇬🇧",
    english: "🇬🇧",
    "English (South Africa)": "🇿🇦",
    "english (south africa)": "🇿🇦",
    "South Africa": "🇿🇦",
    Spanish: "🇪🇸",
    spanish: "🇪🇸",
    "Colombian Spanish": "🇨🇴",
    "colombian spanish": "🇨🇴",
    "Mexican Spanish": "🇲🇽",
    "mexican spanish": "🇲🇽",
    "Costa Rican Spanish": "🇨🇷",
    "costa rican spanish": "🇨🇷",
    "Argentinian Spanish": "🇦🇷",
    "argentinian spanish": "🇦🇷",
    "Spanish (Colombia)": "🇨🇴",
    "spanish (colombia)": "🇨🇴",
    "Spanish (Mexico)": "🇲🇽",
    "spanish (mexico)": "🇲🇽",
    "Spanish (Argentina)": "🇦🇷",
    "spanish (argentina)": "🇦🇷",
    "Spanish (Cuba)": "🇨🇺",
    "spanish (cuba)": "🇨🇺",
    "Spanish (Dominican Republic)": "🇩🇴",
    "spanish (dominican republic)": "🇩🇴",
    French: "🇫🇷",
    french: "🇫🇷",
    "French (Canada)": "🇨🇦",
    "french (canada)": "🇨🇦",
    "Canadian French": "🇨🇦",
    "canadian french": "🇨🇦",
    German: "🇩🇪",
    german: "🇩🇪",
    "German (Austria)": "🇦🇹",
    "german (austria)": "🇦🇹",
    "German (Switzerland)": "🇨🇭",
    "german (switzerland)": "🇨🇭",
    Italian: "🇮🇹",
    italian: "🇮🇹",
    Dutch: "🇳🇱",
    dutch: "🇳🇱",
    "Dutch (Belgium)": "🇧🇪",
    "dutch (belgium)": "🇧🇪",
    Portuguese: "🇵🇹",
    portuguese: "🇵🇹",
    "Portuguese (Brazil)": "🇧🇷",
    "portuguese (brazil)": "🇧🇷",
    "Brazilian Portuguese": "🇧🇷",
    "brazilian portuguese": "🇧🇷",
    Russian: "🇷🇺",
    russian: "🇷🇺",
    Japanese: "🇯🇵",
    japanese: "🇯🇵",
    Chinese: "🇨🇳",
    chinese: "🇨🇳",
    "Chinese (Simplified)": "🇨🇳",
    "chinese (simplified)": "🇨🇳",
    "Chinese (Traditional)": "🇹🇼",
    "chinese (traditional)": "🇹🇼",
    "Mandarin": "🇨🇳",
    "mandarin": "🇨🇳",
    Korean: "🇰🇷",
    korean: "🇰🇷",
    Arabic: "🇪🇬",
    arabic: "🇪🇬",
    "Arabic (Saudi Arabia)": "🇸🇦",
    "arabic (saudi arabia)": "🇸🇦",
    "Arabic (UAE)": "🇦🇪",
    "arabic (uae)": "🇦🇪",
    
    // INDIAN SUBCONTINENT LANGUAGES
    Hindi: "🇮🇳",
    hindi: "🇮🇳",
    Bengali: "🇧🇩",
    bengali: "🇧🇩",
    Tamil: "🇮🇳",
    tamil: "🇮🇳",
    "Tamil (Sri Lanka)": "🇱🇰",
    "tamil (sri lanka)": "🇱🇰",
    Telugu: "🇮🇳",
    telugu: "🇮🇳",
    Marathi: "🇮🇳",
    marathi: "🇮🇳",
    Gujarati: "🇮🇳",
    gujarati: "🇮🇳",
    Punjabi: "🇮🇳",
    punjabi: "🇮🇳",
    Urdu: "🇵🇰",
    urdu: "🇵🇰",
    
    // EUROPEAN LANGUAGES
    Polish: "🇵🇱",
    polish: "🇵🇱",
    Turkish: "🇹🇷",
    turkish: "🇹🇷",
    Ukrainian: "🇺🇦",
    ukrainian: "🇺🇦",
    Swedish: "🇸🇪",
    swedish: "🇸🇪",
    Norwegian: "🇳🇴",
    norwegian: "🇳🇴",
    Danish: "🇩🇰",
    danish: "🇩🇰",
    Finnish: "🇫🇮",
    finnish: "🇫🇮",
    Czech: "🇨🇿",
    czech: "🇨🇿",
    Greek: "🇬🇷",
    greek: "🇬🇷",
    Hungarian: "🇭🇺",
    hungarian: "🇭🇺",
    Romanian: "🇷🇴",
    romanian: "🇷🇴",
    Slovak: "🇸🇰",
    slovak: "🇸🇰",
    Bulgarian: "🇧🇬",
    bulgarian: "🇧🇬",
    Croatian: "🇭🇷",
    croatian: "🇭🇷",
    Serbian: "🇷🇸",
    serbian: "🇷🇸",
    Catalan: "🇪🇸",
    catalan: "🇪🇸",
    
    // ASIAN LANGUAGES
    Indonesian: "🇮🇩",
    indonesian: "🇮🇩",
    Malay: "🇲🇾",
    malay: "🇲🇾",
    Thai: "🇹🇭",
    thai: "🇹🇭",
    Vietnamese: "🇻🇳",
    vietnamese: "🇻🇳",
    
    // AFRICAN LANGUAGES
    Afrikaans: "🇿🇦",
    afrikaans: "🇿🇦",
    Swahili: "🇹🇿",
    swahili: "🇹🇿",
    Zulu: "🇿🇦",
    zulu: "🇿🇦",
    
    // MIDDLE EASTERN LANGUAGES
    Farsi: "🇮🇷",
    farsi: "🇮🇷",
    Persian: "🇮🇷",
    persian: "🇮🇷",
    Hebrew: "🇮🇱",
    hebrew: "🇮🇱",
    
    // AFRICAN REGIONAL
    Mali: "🇲🇱",
    mali: "🇲🇱",
    Bambara: "🇲🇱",
    bambara: "🇲🇱",
    
    // CELTIC LANGUAGES
    Irish: "🇮🇪",
    irish: "🇮🇪",
    Gaeilge: "🇮🇪",
    gaeilge: "🇮🇪",
    Scottish: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
    scottish: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
    "Scottish Gaelic": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
    "scottish gaelic": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
    
    // PACIFIC ISLANDS
    "Tagalog": "🇵🇭",
    "tagalog": "🇵🇭",
    "Filipino": "🇵🇭",
    "filipino": "🇵🇭",
    "Cebuano": "🇵🇭",
    "cebuano": "🇵🇭",
    "English (Philippines)": "🇵🇭",
    "english (philippines)": "🇵🇭",
    "Sinhala": "🇱🇰",
    "sinhala": "🇱🇰",
    "English (Sri Lanka)": "🇱🇰",
    "english (sri lanka)": "🇱🇰",
    "Icelandic": "🇮🇸",
    "icelandic": "🇮🇸",
    "Maltese": "🇲🇹",
    "maltese": "🇲🇹",
    "English (Malta)": "🇲🇹",
    "english (malta)": "🇲🇹",
    "Māori": "🇳🇿",
    "māori": "🇳🇿",
    "Maori": "🇳🇿",
    "maori": "🇳🇿",
    "English (New Zealand)": "🇳🇿",
    "english (new zealand)": "🇳🇿",
    "Samoan": "🇼🇸",
    "samoan": "🇼🇸",
    "Fijian": "🇫🇯",
    "fijian": "🇫🇯",
    "English (Fiji)": "🇫🇯",
    "english (fiji)": "🇫🇯",
    "Hindi (Fiji)": "🇫🇯",
    "hindi (fiji)": "🇫🇯",
    "Tongan": "🇹🇴",
    "tongan": "🇹🇴",
    "English (Tonga)": "🇹🇴",
    "english (tonga)": "🇹🇴",
    "Chamorro": "🇬🇺",
    "chamorro": "🇬🇺",
    "English (Guam)": "🇬🇺",
    "english (guam)": "🇬🇺",
    "Marshallese": "🇲🇭",
    "marshallese": "🇲🇭",
    "English (Marshall Islands)": "🇲🇭",
    "english (marshall islands)": "🇲🇭",
    "Palauan": "🇵🇼",
    "palauan": "🇵🇼",
    "English (Palau)": "🇵🇼",
    "english (palau)": "🇵🇼",
    "Nauruan": "🇳🇷",
    "nauruan": "🇳🇷",
    "English (Nauru)": "🇳🇷",
    "english (nauru)": "🇳🇷",
    "Tuvaluan": "🇹🇻",
    "tuvaluan": "🇹🇻",
    "English (Tuvalu)": "🇹🇻",
    "english (tuvalu)": "🇹🇻",
    "Kirghiz": "🇰🇮",
    "kirghiz": "🇰🇮",
    "English (Kiribati)": "🇰🇮",
    "english (kiribati)": "🇰🇮",
    "Vanuatuan": "🇻🇺",
    "vanuatuan": "🇻🇺",
    "Bislama": "🇻🇺",
    "bislama": "🇻🇺",
    "English (Vanuatu)": "🇻🇺",
    "english (vanuatu)": "🇻🇺",
    "French (Vanuatu)": "🇻🇺",
    "french (vanuatu)": "🇻🇺",
    "Solomon Islands Pidgin": "🇸🇧",
    "solomon islands pidgin": "🇸🇧",
    "English (Solomon Islands)": "🇸🇧",
    "english (solomon islands)": "🇸🇧",
    "Papua New Guinea": "🇵🇬",
    "papua new guinea": "🇵🇬",
    "English (Papua New Guinea)": "🇵🇬",
    "english (papua new guinea)": "🇵🇬",
    "Tok Pisin": "🇵🇬",
    "tok pisin": "🇵🇬",
    
    // CARIBBEAN
    "English (Jamaica)": "🇯🇲",
    "english (jamaica)": "🇯🇲",
    "Jamaican Patois": "🇯🇲",
    "jamaican patois": "🇯🇲",
    "English (Barbados)": "🇧🇧",
    "english (barbados)": "🇧🇧",
    "English (Trinidad and Tobago)": "🇹🇹",
    "english (trinidad and tobago)": "🇹🇹",
    "English (Bahamas)": "🇧🇸",
    "english (bahamas)": "🇧🇸",
    "Haitian Creole": "🇭🇹",
    "haitian creole": "🇭🇹",
    "French (Haiti)": "🇭🇹",
    "french (haiti)": "🇭🇹",
    "English (Dominican Republic)": "🇩🇴",
    "english (dominican republic)": "🇩🇴",
    "English (Cuba)": "🇨🇺",
    "english (cuba)": "🇨🇺",
    
    // EUROPEAN ISLANDS
    "Corsican": "🇫🇷",
    "corsican": "🇫🇷",
    "French (Corsica)": "🇫🇷",
    "french (corsica)": "🇫🇷",
    "Sardinian": "🇮🇹",
    "sardinian": "🇮🇹",
    "Italian (Sardinia)": "🇮🇹",
    "italian (sardinia)": "🇮🇹",
    "Sicilian": "🇮🇹",
    "sicilian": "🇮🇹",
    "Italian (Sicily)": "🇮🇹",
    "italian (sicily)": "🇮🇹",
    "Faroese": "🇫🇴",
    "faroese": "🇫🇴",
    "Danish (Faroe Islands)": "🇫🇴",
    "danish (faroe islands)": "🇫🇴",
    "Greenlandic": "🇬🇱",
    "greenlandic": "🇬🇱",
    "Danish (Greenland)": "🇬🇱",
    "danish (greenland)": "🇬🇱",
    
    // OVERSEAS TERRITORIES
    "English (Bermuda)": "🇧🇲",
    "english (bermuda)": "🇧🇲",
    "English (Cayman Islands)": "🇰🇾",
    "english (cayman islands)": "🇰🇾",
    "English (British Virgin Islands)": "🇻🇬",
    "english (british virgin islands)": "🇻🇬",
    "English (US Virgin Islands)": "🇻🇮",
    "english (us virgin islands)": "🇻🇮",
    "English (Puerto Rico)": "🇵🇷",
    "english (puerto rico)": "🇵🇷",
    "Spanish (Puerto Rico)": "🇵🇷",
    "spanish (puerto rico)": "🇵🇷",
    "English (Aruba)": "🇦🇼",
    "english (aruba)": "🇦🇼",
    "Dutch (Aruba)": "🇦🇼",
    "dutch (aruba)": "🇦🇼",
    "Papiamento": "🇦🇼",
    "papiamento": "🇦🇼",
    "English (Curaçao)": "🇨🇼",
    "english (curaçao)": "🇨🇼",
    "Dutch (Curaçao)": "🇨🇼",
    "dutch (curaçao)": "🇨🇼",
    "French (Martinique)": "🇲🇶",
    "french (martinique)": "🇲🇶",
    "French (Guadeloupe)": "🇬🇵",
    "french (guadeloupe)": "🇬🇵",
    "French (Réunion)": "🇷🇪",
    "french (réunion)": "🇷🇪",
    "French (Mayotte)": "🇾🇹",
    "french (mayotte)": "🇾🇹",
    
    // INDIAN OCEAN
    "English (Seychelles)": "🇸🇨",
    "english (seychelles)": "🇸🇨",
    "French (Seychelles)": "🇸🇨",
    "french (seychelles)": "🇸🇨",
    "Seychellois Creole": "🇸🇨",
    "seychellois creole": "🇸🇨",
    "English (Mauritius)": "🇲🇺",
    "english (mauritius)": "🇲🇺",
    "French (Mauritius)": "🇲🇺",
    "french (mauritius)": "🇲🇺",
    "Mauritian Creole": "🇲🇺",
    "mauritian creole": "🇲🇺",
    "English (Maldives)": "🇲🇻",
    "english (maldives)": "🇲🇻",
    "Dhivehi": "🇲🇻",
    "dhivehi": "🇲🇻",
    "Maldivian": "🇲🇻",
    "maldivian": "🇲🇻",
  };
  
  // Enhanced case-insensitive lookup with normalization
  const normalizedLanguage = language.trim();
  
  // First try exact match
  let flag = mapping[normalizedLanguage];
  if (flag) {
    console.log("🏳️ languageToFlag exact match:", normalizedLanguage, "→", flag);
    return flag;
  }
  
  // Try case-insensitive match
  flag = mapping[normalizedLanguage.toLowerCase()];
  if (flag) {
    console.log("🏳️ languageToFlag lowercase match:", normalizedLanguage, "→", flag);
    return flag;
  }
  
  // Try with first letter capitalized
  const capitalized = normalizedLanguage.charAt(0).toUpperCase() + normalizedLanguage.slice(1).toLowerCase();
  flag = mapping[capitalized];
  if (flag) {
    console.log("🏳️ languageToFlag capitalized match:", normalizedLanguage, "→", capitalized, "→", flag);
    return flag;
  }
  
  // Fallback to globe icon with warning
  console.warn("🌐 languageToFlag: No flag found for language:", normalizedLanguage, "- using globe icon");
  return "🌐";
}

