
/**
 * Maps language names to their most representative country flag emoji.
 * Extend this as needed for new languages.
 */
export function languageToFlag(language: string): string {
  console.log("🏳️ languageToFlag called with:", language);
  
  const mapping: Record<string, string> = {
    English: "🇬🇧",
    "English (South Africa)": "🇿🇦",
    "South Africa": "🇿🇦",
    Spanish: "🇪🇸",
    "Colombian Spanish": "🇨🇴",
    "Mexican Spanish": "🇲🇽",
    "Argentinian Spanish": "🇦🇷",
    "Spanish (Colombia)": "🇨🇴",
    "Spanish (Mexico)": "🇲🇽",
    "Spanish (Argentina)": "🇦🇷",
    French: "🇫🇷",
    "French (Canada)": "🇨🇦",
    "Canadian French": "🇨🇦",
    German: "🇩🇪",
    "German (Austria)": "🇦🇹",
    "German (Switzerland)": "🇨🇭",
    Italian: "🇮🇹",
    Dutch: "🇳🇱",
    "Dutch (Belgium)": "🇧🇪",
    Portuguese: "🇵🇹",
    "Portuguese (Brazil)": "🇧🇷",
    "Brazilian Portuguese": "🇧🇷",
    Russian: "🇷🇺",
    Japanese: "🇯🇵",
    Chinese: "🇨🇳",
    "Chinese (Simplified)": "🇨🇳",
    "Chinese (Traditional)": "🇹🇼",
    "Mandarin": "🇨🇳",
    Korean: "🇰🇷",
    Arabic: "🇪🇬",
    "Arabic (Saudi Arabia)": "🇸🇦",
    "Arabic (UAE)": "🇦🇪",
    Hindi: "🇮🇳",
    Polish: "🇵🇱",
    Turkish: "🇹🇷",
    Ukrainian: "🇺🇦",
    Swedish: "🇸🇪",
    Norwegian: "🇳🇴",
    Danish: "🇩🇰",
    Finnish: "🇫🇮",
    Czech: "🇨🇿",
    Greek: "🇬🇷",
    Hungarian: "🇭🇺",
    Romanian: "🇷🇴",
    Slovak: "🇸🇰",
    Bulgarian: "🇧🇬",
    Croatian: "🇭🇷",
    Serbian: "🇷🇸",
    Catalan: "🇪🇸",
    Indonesian: "🇮🇩",
    Malay: "🇲🇾",
    Thai: "🇹🇭",
    Vietnamese: "🇻🇳",
    Afrikaans: "🇿🇦",
    Farsi: "🇮🇷",
    Persian: "🇮🇷",
    Mali: "🇲🇱",
    Bambara: "🇲🇱",
    Irish: "🇮🇪",
    Gaeilge: "🇮🇪",
    Scottish: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
    "Scottish Gaelic": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
    Hebrew: "🇮🇱",
    // Island countries
    "Tagalog": "🇵🇭",
    "Filipino": "🇵🇭",
    "Cebuano": "🇵🇭",
    "English (Philippines)": "🇵🇭",
    "Sinhala": "🇱🇰",
    "Tamil (Sri Lanka)": "🇱🇰",
    "English (Sri Lanka)": "🇱🇰",
    "Icelandic": "🇮🇸",
    "Maltese": "🇲🇹",
    "English (Malta)": "🇲🇹",
    "Māori": "🇳🇿",
    "English (New Zealand)": "🇳🇿",
    "Samoan": "🇼🇸",
    "Fijian": "🇫🇯",
    "English (Fiji)": "🇫🇯",
    "Hindi (Fiji)": "🇫🇯",
    "Tongan": "🇹🇴",
    "English (Tonga)": "🇹🇴",
    "Chamorro": "🇬🇺",
    "English (Guam)": "🇬🇺",
    "Marshallese": "🇲🇭",
    "English (Marshall Islands)": "🇲🇭",
    "Palauan": "🇵🇼",
    "English (Palau)": "🇵🇼",
    "Nauruan": "🇳🇷",
    "English (Nauru)": "🇳🇷",
    "Tuvaluan": "🇹🇻",
    "English (Tuvalu)": "🇹🇻",
    "Kirghiz": "🇰🇮",
    "English (Kiribati)": "🇰🇮",
    "Vanuatuan": "🇻🇺",
    "Bislama": "🇻🇺",
    "English (Vanuatu)": "🇻🇺",
    "French (Vanuatu)": "🇻🇺",
    "Solomon Islands Pidgin": "🇸🇧",
    "English (Solomon Islands)": "🇸🇧",
    "Papua New Guinea": "🇵🇬",
    "English (Papua New Guinea)": "🇵🇬",
    "Tok Pisin": "🇵🇬",
    "English (Jamaica)": "🇯🇲",
    "Jamaican Patois": "🇯🇲",
    "English (Barbados)": "🇧🇧",
    "English (Trinidad and Tobago)": "🇹🇹",
    "English (Bahamas)": "🇧🇸",
    "Haitian Creole": "🇭🇹",
    "French (Haiti)": "🇭🇹",
    "English (Dominican Republic)": "🇩🇴",
    "Spanish (Dominican Republic)": "🇩🇴",
    "English (Cuba)": "🇨🇺",
    "Spanish (Cuba)": "🇨🇺",
    "Corsican": "🇫🇷",
    "French (Corsica)": "🇫🇷",
    "Sardinian": "🇮🇹",
    "Italian (Sardinia)": "🇮🇹",
    "Sicilian": "🇮🇹",
    "Italian (Sicily)": "🇮🇹",
    "Faroese": "🇫🇴",
    "Danish (Faroe Islands)": "🇫🇴",
    "Greenlandic": "🇬🇱",
    "Danish (Greenland)": "🇬🇱",
    "English (Bermuda)": "🇧🇲",
    "English (Cayman Islands)": "🇰🇾",
    "English (British Virgin Islands)": "🇻🇬",
    "English (US Virgin Islands)": "🇻🇮",
    "English (Puerto Rico)": "🇵🇷",
    "Spanish (Puerto Rico)": "🇵🇷",
    "English (Aruba)": "🇦🇼",
    "Dutch (Aruba)": "🇦🇼",
    "Papiamento": "🇦🇼",
    "English (Curaçao)": "🇨🇼",
    "Dutch (Curaçao)": "🇨🇼",
    "French (Martinique)": "🇲🇶",
    "French (Guadeloupe)": "🇬🇵",
    "French (Réunion)": "🇷🇪",
    "French (Mayotte)": "🇾🇹",
    "English (Seychelles)": "🇸🇨",
    "French (Seychelles)": "🇸🇨",
    "Seychellois Creole": "🇸🇨",
    "English (Mauritius)": "🇲🇺",
    "French (Mauritius)": "🇲🇺",
    "Mauritian Creole": "🇲🇺",
    "English (Maldives)": "🇲🇻",
    "Dhivehi": "🇲🇻",
    "Maldivian": "🇲🇻",
    // add more or tune as needed
  };
  
  // Handle case-insensitive lookup
  const normalizedLanguage = language.charAt(0).toUpperCase() + language.slice(1).toLowerCase();
  const flag = mapping[normalizedLanguage] || mapping[language] || "🌐";
  console.log("🏳️ languageToFlag result:", language, "→", normalizedLanguage, "→", flag);
  return flag;
}
