
-- Add Filipino idioms and sayings
INSERT INTO phrases (phrase_text, language, pronunciation, correct_meaning, incorrect1, incorrect2, difficulty, notes) VALUES
-- Filipino idioms and sayings
('Ang hindi marunong lumingon sa pinanggalingan ay hindi makararating sa paroroonan', 'filipino', 'ang hin-di ma-ru-nong lu-mi-ngon sa pi-nang-ga-li-ngan ay hin-di ma-ka-ra-ra-ting sa pa-ro-roo-nan', 'Those who do not look back to where they came from will not reach their destination', 'People should always walk backwards', 'Looking around helps with navigation', 5, 'Deep Filipino proverb about remembering your roots and heritage'),
('Kapag may tiyaga, may nilaga', 'filipino', 'ka-pag may ti-ya-ga, may ni-la-ga', 'With patience and perseverance, you will be rewarded', 'Cooking soup requires patience', 'Good food takes time to prepare', 3, 'Popular saying about patience leading to success'),
('Ang taong nagigipit, sa patalim kumakapit', 'filipino', 'ang ta-ong na-gi-gi-pit, sa pa-ta-lim ku-ma-ka-pit', 'A desperate person will resort to dangerous measures', 'Sharp objects are dangerous to hold', 'People should avoid knives when scared', 4, 'Warns about desperate actions in difficult situations'),
('Nasa huli ang pagsisisi', 'filipino', 'na-sa hu-li ang pag-si-si-si', 'Regret comes at the end / Hindsight is 20/20', 'Bad things happen at night', 'The last person is always sorry', 3, 'About learning from mistakes too late'),
('Ang hindi lumingon sa pinanggalingan, walang makakamtan na patutunguhan', 'filipino', 'ang hin-di lu-mi-ngon sa pi-nang-ga-li-ngan, wa-lang ma-ka-kam-tan na pa-tu-tu-ngu-han', 'One who forgets their origin will achieve nothing in their destination', 'People who don\'t look around get lost', 'Walking without looking is dangerous', 4, 'About honoring your past to succeed in the future'),
('Pag may isinuksok, may madudukot', 'filipino', 'pag may i-si-nuk-sok, may ma-du-du-kot', 'What you save/invest today, you can use tomorrow', 'Hiding things in pockets is smart', 'You can find things by searching', 3, 'About saving and preparation for the future'),
('Ang batang maagagin, sa gulang ay magiging tamarin', 'filipino', 'ang ba-tang ma-a-ga-gin, sa gu-lang ay ma-gi-ging ta-ma-rin', 'A child who wakes up early will be lazy when older', 'Early risers become tired adults', 'Children need lots of sleep to grow', 2, 'Ironic saying that contradicts the usual advice about early rising'),
('Kung walang tiyaga, walang nilaga', 'filipino', 'kung wa-lang ti-ya-ga, wa-lang ni-la-ga', 'Without patience and effort, there are no results', 'You need ingredients to cook soup', 'Cooking requires fire and water', 3, 'Emphasizes that success requires patience and hard work'),
('Aanhin pa ang damo kung patay na ang kabayo', 'filipino', 'a-a-nhin pa ang da-mo kung pa-tay na ang ka-ba-yo', 'What good is grass when the horse is already dead? / Too little, too late', 'Dead animals cannot eat food', 'Horses only eat fresh grass', 4, 'About offering help when it\'s already too late'),
('Habang maikli ang kumot, matutong mamaluktot', 'filipino', 'ha-bang mai-kli ang ku-mot, ma-tu-tong ma-ma-luk-tot', 'When the blanket is short, learn to curl up', 'Short blankets are uncomfortable', 'People should buy bigger blankets', 4, 'About adapting to limitations and making do with what you have'),
('Ang hindi marunong magmahal sa sariling wika, ay higit pa sa hayop at malansang isda', 'filipino', 'ang hin-di ma-ru-nong mag-ma-hal sa sa-ri-ling wi-ka, ay hi-git pa sa ha-yop at ma-lan-sang is-da', 'One who does not love their own language is worse than animals and rotten fish', 'Animals cannot speak human languages', 'Fish smell bad when they rot', 5, 'José Rizal\'s famous quote about loving your native language'),
('Walang matimtimang birhen sa matiyagang manalangin', 'filipino', 'wa-lang ma-tim-ti-mang bir-hen sa ma-ti-ya-gang ma-na-la-ngin', 'No demure maiden can resist a persistent suitor', 'Religious people pray very quietly', 'Patient prayer is always answered', 4, 'About persistence in courtship and love');
