// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ayfmkmnecfjyhdutxfjp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5Zm1rbW5lY2ZqeWhkdXR4ZmpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTAyODYsImV4cCI6MjA2NTQ4NjI4Nn0.YrJzG57un3Ym-vhgyPhnIKmiRS6zPdVqUsrDXtfsoC4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);